#RUN aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 165485842251.dkr.ecr.ap-south-1.amazonaws.com
FROM 165485842251.dkr.ecr.ap-south-1.amazonaws.com/care-dev-php:php-8.2
CMD ["php-fpm"]
